# Makefile.osx
CFLAGS+= -DTARGET_OS_MAC
CXXFLAGS+= -ObjC++
CXXFLAGS+= -std=c++11 -stdlib=libc++

LDFLAGS+= -framework OpenGL -framework xdispatch -framework Cocoa -framework IOKit
LDFLAGS+= -lpthread -lc++
